### ISSUE TITLE
Can't support language "tur" Turkish in OCREngine 2

### ISSUE THREAD

**Issue by aedikyamac** [DavideViolante/ocr-space-api-wrapper#19]

**Comment by DavideViolante** [comment]
Please explain the problem. See the [official docs](https://ocr.space/OCRAPI#PostParameters) for more info.

**Comment by aedikyamac** [comment]
`const res1 = await ocrSpace(MY_IMAGE_URL, {language: 'tur'}).then(res => {
	console.log(res)
})`
this code succesfully works but when i use OCREngine 2 

`const res1 = await ocrSpace("MY_IMAGE_URL", {language: 'tur', OCREngine: 2}).then(res => {
	console.log(res)
})` 
it prints: `{
  OCRExitCode: 99,
  IsErroredOnProcessing: true,
  ErrorMessage: [ "Value for parameter 'language' is invalid" ],
  ProcessingTimeInMilliseconds: '31'
}`

**Comment by DavideViolante** [comment]
First of all you don't need to use .then if you are using await.
The correct code is:
```js
async function main() {
  const res = await ocrSpace(MY_IMAGE_URL, {language: 'tur'})
  console.log(res)
}
```

Then the exit code is not dependant to this repository, but this is just a wrapper to the OCR Space service.
Maybe the tur language is not supported by OCREngine 2, try using Engine 1.

From the docs about Engine 2:
```
Engine2 has automatic Western language detection, so this value (language) will be ignored.
...
- Language auto-detect. It does not matter what OCR language you select, as long as it uses Latin characters
```

By the way I'm always using Engine 1 and is super efficient for me.

**Comment by aedikyamac** [comment]
Yeah, i removed language value and it worked, thanks sir.
