### ISSUE TITLE
Error in axios, 403 forbidden

### ISSUE THREAD

**Issue by Anjali985** [DavideViolante/ocr-space-api-wrapper#4]
Hi team ,
i am getting this error:
(node:28132) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by DavideViolante** [comment]
Please post your code here.

**Comment by Anjali985** [comment]
![image](https://user-images.githubusercontent.com/57216035/102445891-8eab0280-4052-11eb-8388-31e9f5e73671.png)
this is my code i am trying to call ocrspace api but getting undefined and it not navigating to next line.. and getting above error. please help me out..
thanks in advance

**Comment by DavideViolante** [comment]
Is FilePath correct? Try to print it out before the call.
Try also these variants:
- `await ocrSpaceApi(FilePath)`
- `await ocrSpaceApi('/file/path')`
- `await ocrSpace('http://dl.a9t9.com/ocrbenchmark/eng.png')`

The last one must work, if the others don't, the filepath is wrong

**Comment by Anjali985** [comment]
yeah.. file path is correct but every time it goes to error, below is the console.error 
Error: Request failed with status code 403
    at createError (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\ocr-space\node_modules\ocr-space-api-wrapper\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Anjali985** [comment]
request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        connect: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 7,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: true,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.ocr.space',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.ocr.space',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 1742,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.ocr.space',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'api.ocr.space',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 1742,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'POST /parse/image HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: multipart/form-data; boundary=--------------------------397743066071839727741503\r\napikey: 216721bdde88957\r\nUser-Agent: axios/0.21.0\r\nHost: api.ocr.space\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/parse/image',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'Forbidden',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://api.ocr.space/parse/image',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 54609,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://api.ocr.space/parse/image' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        apikey: [Array],
        'user-agent': [Array],
        host: [Array] } },
  response:
   { status: 403,
     statusText: 'Forbidden',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        server: 'Microsoft-IIS/10.0',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET',
        date: 'Thu, 17 Dec 2020 08:43:17 GMT',
        connection: 'close',
        'content-length': '88' },
     config:
      { url: 'https://api.ocr.space/parse/image',
        method: 'post',
        data: [FormData],
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
        validateStatus: [Function: validateStatus] },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: true,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /parse/image HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: multipart/form-data; boundary=--------------------------397743066071839727741503\r\napikey: 216721bdde88957\r\nUser-Agent: axios/0.21.0\r\nHost: api.ocr.space\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/parse/image',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      'You may only perform this action upto maximum 500 number of times within 86400 seconds' },
  isAxiosError: true,
  toJSON: [Function: toJSON] }

**Comment by DavideViolante** [comment]
The error is `'You may only perform this action upto maximum 500 number of times within 86400 seconds'`
It's the limit of OCR Space free API, there are 500 calls per day ([see docs](https://ocr.space/OCRAPI))

**Comment by Anjali985** [comment]
okay thanks @DavideViolante  :)

**Comment by Anjali985** [comment]
can't we get the start index and end index ?? just like google cloud ?

**Comment by DavideViolante** [comment]
You need to visit https://ocr.space/OCRAPI for info about the API. My lib is just a nodejs wrapper.
