### ISSUE TITLE
Better TypeScript support

### ISSUE THREAD

**Issue by jerrycool123** [DavideViolante/ocr-space-api-wrapper#66]
The `options` parameter and the return type of the function `ocrSpace()` are both `any` now.
```ts
// index.ts
declare module "ocr-space-api-wrapper" {
    export function ocrSpace(input: string, options?: any): any;
}
```

Can you make the type definition more accurate? Thank you very much!

**Comment by DavideViolante** [comment]
Thank you for the issue, you can try the v2.3.0 version and let me know if it works correctly.
